# -*- coding: utf-8 -*-
"""Chap1Ex4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PflT08DFm5qDRKFHGymDclI-kzHZeEQ
"""

x = ("Railey")
y = (" Anthony")
z = (" Inductivo")
result = (x + y + z)
print(result)
