# -*- coding: utf-8 -*-
"""Chap1Ex5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PflT08DFm5qDRKFHGymDclI-kzHZeEQ
"""

radius = input("Input radius of circle: ")
pi = 3.141592
aoc = pi * float(radius)**2
print("The area of the circle is:", aoc)
