# -*- coding: utf-8 -*-
"""Chap1Ex3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PflT08DFm5qDRKFHGymDclI-kzHZeEQ
"""

import datetime
current_date_time = datetime.datetime.now()
print("The current date is", current_date_time.strftime("%Y-%m-%d"))
print("The current time is", current_date_time.strftime("%I:%M:%S"))