# -*- coding: utf-8 -*-
"""Chap2Ex2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PflT08DFm5qDRKFHGymDclI-kzHZeEQ
"""

import sys
print("The Python version you are using is", sys.version)