# -*- coding: utf-8 -*-
"""Chap1Ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PflT08DFm5qDRKFHGymDclI-kzHZeEQ
"""

print(str("Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky."))
print(str("Twinkle, twinkle, little star, How I wonder what you are"))